// AUTO-GENERATED by vue-zero scan — do not edit
import r0 from './api/activities.js'
import r1 from './api/agents.js'
import r2 from './api/auth.js'
import r3 from './api/claude.js'
import r4 from './api/commands.js'
import r5 from './api/console.js'
import r6 from './api/context.js'
import r7 from './api/dashboard.js'
import r8 from './api/lead.js'
import r9 from './api/monitor.js'
import r10 from './api/projects.js'
import r11 from './api/push.js'
import r12 from './api/system.js'
import r13 from './api/users.js'

export default function register(app) {
  app.route('/api/activities', r0)
  app.route('/api/agents', r1)
  app.route('/api/auth', r2)
  app.route('/api/claude', r3)
  app.route('/api/commands', r4)
  app.route('/api/console', r5)
  app.route('/api/context', r6)
  app.route('/api/dashboard', r7)
  app.route('/api/lead', r8)
  app.route('/api/monitor', r9)
  app.route('/api/projects', r10)
  app.route('/api/push', r11)
  app.route('/api/system', r12)
  app.route('/api/users', r13)
}
