// AUTO-GENERATED by vue-zero scan — do not edit
import r0 from './api/activities.js'
import r1 from './api/agents.js'
import r2 from './api/auth.js'
import r3 from './api/claude.js'
import r4 from './api/commands.js'
import r5 from './api/context.js'
import r6 from './api/dashboard.js'
import r7 from './api/lead.js'
import r8 from './api/projects.js'
import r9 from './api/users.js'

export default function register(app) {
  app.route('/api/activities', r0)
  app.route('/api/agents', r1)
  app.route('/api/auth', r2)
  app.route('/api/claude', r3)
  app.route('/api/commands', r4)
  app.route('/api/context', r5)
  app.route('/api/dashboard', r6)
  app.route('/api/lead', r7)
  app.route('/api/projects', r8)
  app.route('/api/users', r9)
}
